### ISSUE TITLE
raygui submodule configured incorrectly

### ISSUE THREAD

**Issue by darthdeus** [ryupold/examples-raylib.zig#1]
I needed to change `.gitmodules` to the following for it to work, the `path = src/raygui` was missing

```
[submodule "src/raylib"]
	path = src/raylib
	url = https://github.com/ryupold/raylib.zig
[submodule "src/raygui"]
	path = src/raygui     <-- added this
	url = https://github.com/ryupold/raygui.zig
```

I'm not sure if this is the correct solution, but it made everything work.

**Comment by ryupold** [comment]
Oh, that's why it showed up in the Github Code Browser without a link.
Thanks for finding the problem 🙂
