### ISSUE TITLE
Not possible to build examples anymore with zig 0.11.0-dev.2652+

### ISSUE THREAD

**Issue by alfredbaudisch** [ryupold/examples-raylib.zig#3]
I am just getting started with Zig, and the first version I got is  `0.11.0-dev.2652`. With it, it's not possible to build your wasm examples anymore:

`lib.setOutputDir(webCachedir);` https://github.com/ryupold/examples-raylib.zig/blob/main/build.zig#L123
```
error: no field or member function named 'setOutputDir' in 'Build.CompileStep'
```

Also `lib.install` doesn't work anymore, but this one I managed to changed to `b.installArtifact(lib)`. But still, due to not being able to setOutputDir, it's not possible to build for web anymore.

I tried installing Zig 0.10, but then there's even more incompatibilities. Which version of `0.11.*` are you targeting currently?

Thanks!

**Comment by alfredbaudisch** [comment]
It was removed last week: https://github.com/ziglang/zig/commit/5a8b1bde5b3ce2628a8e490c3cef9fcc95f94ab5

**Comment by ryupold** [comment]
Hey, thanks for testing with the newest version. My last update was with the 0.11 version from 21th March and until now I did not update. I see that this problem is also in the build.zig of the raylib repository as they are also using setOutDir. But where can I now set the output directory?

**Comment by alfredbaudisch** [comment]
I'm new to the zig ecosystem too.

It seems that now we have to use `b.installDirectory(.{ .source_dir = "", .install_dir = .{ .custom = webCachedir }, .install_subdir = webCachedir });`

But then how to mimic what was a simple single directory with "setOutputDir"? It seems complicated now.

**Comment by ryupold** [comment]
I couldn't figure out how to set the output dir otherwise but with `installArtifact` as you mentioned in the beginning.       
```zig
const libraryOutputFolder = "zig-out/lib/";
// this installs the lib (libraylib-zig-examples.a) to the `libraryOutputFolder` folder
b.installArtifact(lib);
```
then I pass this folder also to the emcc build so it can find the static library.
I liked it better the way it was before but now it works again at least.

**Comment by alfredbaudisch** [comment]
Thanks for sharing, I'm learning alongside about the zib builder.
